# Generated by Django 6.0.3 on 2026-06-02 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("nacionalidade", models.CharField(max_length=100)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Filme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("sinopse", models.TextField()),
                ("ano_lancamento", models.IntegerField()),
                ("duracao_minutos", models.IntegerField()),
                ("classificacao", models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("descricao", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Realizador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("nacionalidade", models.CharField(max_length=100)),
                ("data_nascimento", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FilmeAtor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("personagem", models.CharField(max_length=100)),
                (
                    "ator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="filmes.ator"
                    ),
                ),
                (
                    "filme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="filmes.filme"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="filme",
            name="atores",
            field=models.ManyToManyField(
                related_name="filmes", through="filmes.FilmeAtor", to="filmes.ator"
            ),
        ),
        migrations.AddField(
            model_name="filme",
            name="generos",
            field=models.ManyToManyField(related_name="filmes", to="filmes.genero"),
        ),
        migrations.AddField(
            model_name="filme",
            name="realizador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filmes",
                to="filmes.realizador",
            ),
        ),
    ]
