# Generated by Django 6.0.3 on 2026-06-02 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("filmes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filmeator",
            name="personagem",
        ),
    ]
