# Generated by Django 6.0.3 on 2026-04-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_competencia_tecnologia_projeto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("pagina_lusofona", models.URLField()),
                ("foto", models.ImageField(upload_to="docentes/")),
            ],
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="docentes",
            field=models.ManyToManyField(to="portfolio.docente"),
        ),
    ]
