# Generated by Django 6.0.3 on 2026-04-07 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_tfc"),
    ]

    operations = [
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                ("data", models.DateField()),
                ("imagem", models.ImageField(upload_to="makingof/")),
                ("decisao", models.TextField()),
                ("erro", models.TextField()),
                ("correcao", models.TextField()),
                (
                    "projeto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.projeto",
                    ),
                ),
                (
                    "tecnologia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.tecnologia",
                    ),
                ),
                (
                    "unidade_curricular",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
