# Generated by Django 6.0.3 on 2026-04-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_makingof"),
    ]

    operations = [
        migrations.AddField(
            model_name="tfc",
            name="areas",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="imagem",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="licenciatura",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="tfc",
            name="link_pdf",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="palavras_chave",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tfc",
            name="sumario",
            field=models.TextField(blank=True),
        ),
    ]
