# Generated by Django 6.0.3 on 2026-04-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0008_tfc_areas_tfc_imagem_tfc_licenciatura_tfc_link_pdf_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tecnologia",
            name="logotipo",
            field=models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
        ),
    ]
