# Generated by Django 6.0.3 on 2026-04-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_alter_tecnologia_logotipo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tfc",
            name="classificacao",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="descricao",
        ),
        migrations.AlterField(
            model_name="tfc",
            name="ano",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="tecnologias",
            field=models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
        ),
    ]
