# Generated by Django 6.0.3 on 2026-04-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_remove_tfc_classificacao_remove_tfc_descricao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidadecurricular",
            name="codigo",
            field=models.CharField(default="sem_codigo", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="ects",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="docentes",
            field=models.ManyToManyField(blank=True, to="portfolio.docente"),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="ucs/"),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="semestre",
            field=models.CharField(max_length=20),
        ),
    ]
