# Generated by Django 6.0.3 on 2026-04-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_unidadecurricular_codigo_unidadecurricular_ects_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="competencias",
            field=models.ManyToManyField(blank=True, to="portfolio.competencia"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="github_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="projetos/"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="tecnologias",
            field=models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="video_demo",
            field=models.URLField(blank=True, null=True),
        ),
    ]
