# Generated by Django 6.0.3 on 2026-04-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0012_alter_projeto_competencias_alter_projeto_github_link_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="docente",
            name="foto",
            field=models.ImageField(blank=True, upload_to="docentes/"),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="imagem",
            field=models.ImageField(blank=True, upload_to="makingof/"),
        ),
    ]
