# Generated by Django 6.0.3 on 2026-04-27 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0014_tipotecnologia_alter_tecnologia_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tecnologia",
            name="tipo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio.tipotecnologia",
            ),
        ),
    ]
