# Generated by Django 6.0.3 on 2026-04-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0015_alter_tecnologia_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tecnologia",
            name="tipo",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
