# Generated by Django 6.0.3 on 2026-04-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0016_alter_tecnologia_tipo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TipoTecnologia",
        ),
    ]
